config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :sites
  root "sites#index"

  get "home/index", path: :currencyconverter

  localized do
    get "home/index", path: :currencyconverter
  end
  

end

app/models/site.rb
class Site < ActiveRecord::Base
	has_many :articles
	has_many :links
	has_one :scheduler
	has_one :score

	validates :site_url, presence: true, uniqueness: true

	#scope :zero_confidence, -> { where(confidence: 0) }

	after_create :schedule_site_crawl, :update_feed #, :add_score

	#def self.search(query)
	#	Article.search_by_title_and_keywords(query)
	#end

	#def add_score
	#	Score.calculate_score(self.id)
	#end

	def update_feed #nem sempre consegue pegar o feed, ex.: escoladinheiro.com
		self.update(feed:  FeedSearcher.search(self.site_url).first) || ""
	end

	def schedule_site_crawl
		Scheduler.create(schedule: self.id, site_id: self.id)
	end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource
  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all

    if params[:query]
      @query = params[:query]      
      @search = Article.search(@query).limit(10)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @article_id = params[:article_id] rescue nil
    respond_to do |format|
      format.html
      format.js #{ render 'about.js' }
    end
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render action: 'show', status: :created, location: @site }
      else
        format.html { render action: 'new' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:name, :site_url, :feed, :description)
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_about.html.erb
<div id='about'>
	<div class="media">
      	<div class="media-body">
			<h4 class="text-warning">
				<%= @site.name %>			
			</h4>

			<h5 class="text-warning">
				<i class='glyphicon glyphicon-star'></i>
				<strong><%= @site.confidence %>%</strong> Confidence Index Breakdown
			</h5>

			<div class="info">
				<h5 class="text-muted">
					<i class="octicon octicon-globe"></i>
					Access rank: <%= @site.score.alexa %>
				</h5>
				
				<h5 class="text-muted">
					<i class="octicon octicon-link"></i>
					Google rank: <%= @site.score.google %>
				</h5>

				<h5 class="text-muted">
					<i class="octicon octicon-pulse"></i>
					SEO rank: <%= @site.score.moz %>
				</h5>

				<h5 class="text-muted">
					<i class="octicon octicon-file-text"></i>
					Articles: +<%= @site.articles.length %>
				</h5>

				<h5 class="text-muted">
					<i class="octicon octicon-repo"></i>
					Books: ~<%= @site.score.books %>
			</div>
		</div>
</div>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :site_url %><br>
    <%= f.text_field :site_url %>
  </div>
  <div class="field">
    <%= f.label :feed %><br>
    <%= f.text_field :feed %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/_search.html.erb
<% if @search.size == 0 %>
  <div id="search">
        <div id="link" class="media">
          <div class="media-body">
            <h4 class="text-info">
              Your search didn't return a result (this time),
              Grab yourself a <i class="text-warning octicon octicon-beer"></i>,
              and try one of these:
            </h4>
            </div>
        </div>
    </div>
<% else %>
  <div id="search">
    <div class="text-muted">
        Tip: click the
        <i class='text-muted glyphicon glyphicon-info-sign'></i>
        to see the <span class="text-warning">confidence index</span> breakdown.
    </div>  
    <% @search.each do |result| %>
      <div id="link" class="media">

        <div class="media-body">
          <h4 class="text-info">
            <%= link_to result.title, result.article_url, target: "_blank" %>
          </h4>

            <h5 class="text-success"><%= result.site.site_url %>
                
            </h5>

            <h5 class="text-warning">Confidence Index
              <% star = result.site.confidence.to_f %>
              <% star_to_five = ((star/10)/2).round %>
              <% star_to_five.times do %>
                <span class='glyphicon glyphicon-star'></span>
              <%end %>

              <% no_star = 5 - star_to_five %>
              <% no_star.times do %>
                <span class='text-muted glyphicon glyphicon-star-empty'></span>
              <% end %>
              
              <%= link_to "", 
              site_path(id: result.site.id, article_id: result.id), 
              remote: true, 
              title: "click to understand",
               class: "text-muted glyphicon glyphicon-info-sign" %>
               
            </h5>
            <div id="<%= result.id %>" class="confidenceindex">
            
            </div>
          </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<div class="jumbotron">   
  <div class="container">
    <br><br><br><br>    

      <div class="row">
        <div class="col-md-4"></div>
        <div id="top" class="col-md-7">

          <h1 style="color: #fff; text-shadow: 1px 2px 3px #666;" class="text-center">
            <strong> Search </strong>
          </h1>
          <h1 style="color: #fff; text-shadow: 1px 2px 3px #666;" class="text-center">
            <strong>Business and Financial Advice</strong>
          </h1>
          <h2 style="text-shadow: 1px 2px 3px #000;" class="text-warning text-right">
            Check out how trustworthy it is 
            <small class="text-warning glyphicon glyphicon-star"></small>
          </h2>

          <br><br><br>

            <div id="searcher1">
              <%= form_tag sites_path, class: "form-search", remote: true, method: :get do %>
                <div class="input-group">

                  <%= text_field_tag :query, params[:query], class: "form-control search-query input-lg",  placeholder: "...", autofocus: "autofocus"  %>

                      <span class="input-group-btn">
                        <button type="submit" id="bob" class="btn btn-success btn-lg">
                          <i class="glyphicon glyphicon-search"></i>
                        </button>
                      </span>
                 </div>
              <% end %>
            </div>

            <h3 style="color: #fff; text-shadow: 1px 2px 3px #000;">
          <% numbers = Article.all.size %>
          <% numbers = numbers.to_s.split(/(\d)/) %>
          <% numbers.each do |n| %>
            <% if n != "" %>
            <kbd><%= n %></kbd>
            <% end %>
          <% end %>

          Free articles from our buddies
          </h3>

          </div>
          <div class="col-md-1"></div>
        </div>
    </div>
</div>

<div class="container" id="presentation">
  <div class="row">
    <div class="col-md-4">
      <div class="page-header">
        <h1 class="text-center">
          <i class="octicon octicon-sync" style="font-size: 48px;"></i> 
          Convert
        </h1>
      </div>
        <h3 class="text-center">The Best Currency Converter</h3>
        <h4 class="text-muted text-center">
          Find out how much is your money worth today.            
        </h4>
        <br>
        <p class="text-center">
          <a href="/currencyconverter" class="btn btn-success btn-lg" role="button">Convert It</a>
        </p>          
    </div>

    <div class="col-md-4">
      <div class="page-header">
        <h1 class="text-center">
          <i class="octicon octicon-telescope" style="font-size: 48px;"></i> 
          Find Articles 
        </h1>
      </div>
        <h3 class="text-center">Business and Finance Advice</h3>
        <h4 class="text-muted text-center">
          <% numbers = Article.all.size %>
          <% numbers = numbers.to_s.split(/(\d)/) %>
          <% numbers.each do |n| %>
            <% if n != "" %>
            <small><kbd><%= n %></kbd></small>
            <% end %>
          <% end %>
          articles from experts -
          hands on ideas to apply in your life and business.            
        </h4>
        <br>
        <p class="text-center">
          <a href="#top" class="btn btn-success btn-lg" role="button">Search Now</a>
        </p>          
    </div>

    <div class="col-md-4">
        <div class="page-header">
          <h1 class="text-center">
            <i class="octicon octicon-graph" style="font-size: 48px;"></i> 
            Get Statistics
          </h1>
        </div>
        <h3 class="text-center">Is it trustworthy?</h3>
        <h4 class="text-muted text-center">
          The Confidence Index helps you
          infer how much trust to put 
          on an article's publisher.
        </h4>
        <br>
        <p class="text-center">
          <a class="btn btn-success btn-lg" role="button">Learn more</a>
        </p>
    </div>
    <div class="col-md-1"></div>
  </div>
</div>

<div class="container" role="main">
  <br>
  <div class="row">

    <div class="col-md-1">
      
          <div id="loading-indicator"  class="hidden">
              <%= image_tag("loading.gif", class: "pull-left") %>
          </div>
      
    </div>

    <div id="column1" class="col-md-7">

      <div id="searcher2" class="hidden">
        <%= form_tag sites_path, class: "form-search", remote: true, method: :get do %>
          <div class="input-group">

            <%= text_field_tag :query, params[:query], class: "form-control search-query",  placeholder: "..." %>

                <span class="input-group-btn">
                  <button type="submit" class="btn btn-success">
                    <i class="glyphicon glyphicon-search"></i>
                  </button>
                </span>
           </div>
        <% end %>
      </div>

      <div class="results"></div>

    </div>

    <div class="col-md-4">
      <div id='side'>
        <div class="media">
          
          <div class="media-body">

          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @site.name %>
</p>

<p>
  <strong>Site url:</strong>
  <%= @site.site_url %>
</p>

<p>
  <strong>Feed:</strong>
  <%= @site.feed %>
</p>

<p>
  <strong>Description:</strong>
  <%= @site.description %>
</p>

<p>
  <strong>Confidence:</strong>
  <%= @site.confidence %>
</p>

<p>
  <% if can? :update, @site %>
    <%= link_to 'Edit', edit_site_path(@site) %> |
  <% end %>
  <% if can? :destroy, @site %>
    <%= link_to "Destroy", @site, :method => :delete, :confirm => "Are you sure?" %> |
  <% end %>
  	<%= link_to 'Back', sites_path %>
</p>

app/views/sites/show.js.erb
$(function () {
  if ($('#about').length > 0) { 
    $('#about').remove();
    $("#<%= @article_id %>.confidenceindex").append('<%= j render "about" %>');  
  } else {
    $("#<%= @article_id %>.confidenceindex").append('<%= j render "about" %>');
  }
});